name: Build piko patches (JAR)

on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (this repo)
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Build (JAR)
        run: |
          chmod +x ./gradlew || true
          ./gradlew --no-daemon clean build

      - name: Upload artifact (piko JAR)
        uses: actions/upload-artifact@v4
        with:
          name: piko-patches-jar
          path: build/libs/*.jar
          if-no-files-found: error
          retention-days: 14
